
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: "mssql-container"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Fatopa_123"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
